import React from 'react';
import { X, Code2, Cpu, Sparkles, BookOpen, Layers } from 'lucide-react';

interface AboutModalProps {
  isOpen: boolean;
  onClose: () => void;
  onNavigate: (view: 'landing' | 'visualizer' | 'library' | 'learn' | 'challenges' | 'about') => void;
}

export const AboutModal: React.FC<AboutModalProps> = ({ isOpen, onClose, onNavigate }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/75 backdrop-blur-sm animate-in fade-in">
      <div className="w-full max-w-2xl rounded-2xl border border-indigo-900/80 bg-[#0d1326] p-6 sm:p-8 shadow-2xl space-y-6 max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-indigo-950 pb-4">
          <div className="flex items-center gap-2.5">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-indigo-600 text-white font-mono text-xs font-bold">
              &lt;&gt;
            </div>
            <div>
              <h2 className="text-lg font-bold text-white">About Algorithm Visualizer</h2>
              <p className="text-xs text-indigo-400 font-mono">Pedagogical Framework for Computer Science</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="rounded-lg p-1 text-slate-400 hover:text-white hover:bg-slate-800 transition-colors"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Philosophy */}
        <div className="space-y-3">
          <h3 className="text-sm font-semibold text-slate-200">The Core Relationship</h3>
          <div className="p-3.5 rounded-xl bg-[#090d1c] border border-indigo-950 text-xs font-mono text-center flex flex-wrap items-center justify-center gap-2">
            <span className="text-sky-300 font-bold">INPUT</span>
            <span className="text-slate-600">→</span>
            <span className="text-indigo-300 font-bold">ALGORITHM</span>
            <span className="text-slate-600">→</span>
            <span className="text-purple-300 font-bold">VISUALIZATION</span>
            <span className="text-slate-600">→</span>
            <span className="text-emerald-300 font-bold">CODE</span>
            <span className="text-slate-600">→</span>
            <span className="text-amber-300 font-bold">EXPLANATION</span>
            <span className="text-slate-600">→</span>
            <span className="text-pink-300 font-bold">UNDERSTANDING</span>
          </div>
          <p className="text-xs text-slate-300 leading-relaxed">
            Computer science education frequently relies on memorizing complex nested loops or static textbook code listings.
            Algorithm Visualizer transforms abstract asymptotic theorems into tangible, interactive step-by-step simulations where students can manipulate data, alter execution speeds, and inspect invariants.
          </p>
        </div>

        {/* Feature Highlights */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">
          <div className="p-3 rounded-xl bg-slate-900/60 border border-slate-800 space-y-1">
            <div className="font-semibold text-white flex items-center gap-1.5">
              <Cpu className="h-3.5 w-3.5 text-sky-400" />
              <span>Deterministic Step Engines</span>
            </div>
            <p className="text-slate-400 text-[11px] leading-relaxed">
              Every comparison, swap, partition, and recursion frame is generated by true algorithm simulators.
            </p>
          </div>

          <div className="p-3 rounded-xl bg-slate-900/60 border border-slate-800 space-y-1">
            <div className="font-semibold text-white flex items-center gap-1.5">
              <Code2 className="h-3.5 w-3.5 text-indigo-400" />
              <span>Multi-Language Sync</span>
            </div>
            <p className="text-slate-400 text-[11px] leading-relaxed">
              View synchronized execution highlights in Python, JavaScript, C++, or Java.
            </p>
          </div>
        </div>

        {/* Keyboard Shortcuts */}
        <div className="space-y-2 border-t border-indigo-950 pt-4">
          <div className="text-xs font-semibold text-slate-300">Keyboard Shortcuts</div>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs font-mono">
            <div className="bg-slate-900 p-2 rounded border border-slate-800">
              <div className="text-slate-500 text-[10px]">Play / Pause</div>
              <div className="text-slate-200 font-bold">Space</div>
            </div>
            <div className="bg-slate-900 p-2 rounded border border-slate-800">
              <div className="text-slate-500 text-[10px]">Step Forward</div>
              <div className="text-slate-200 font-bold">→ Right</div>
            </div>
            <div className="bg-slate-900 p-2 rounded border border-slate-800">
              <div className="text-slate-500 text-[10px]">Step Back</div>
              <div className="text-slate-200 font-bold">← Left</div>
            </div>
            <div className="bg-slate-900 p-2 rounded border border-slate-800">
              <div className="text-slate-500 text-[10px]">Quick Search</div>
              <div className="text-slate-200 font-bold">/ Slash</div>
            </div>
          </div>
        </div>

        {/* Close Button */}
        <div className="pt-2 flex justify-end">
          <button
            onClick={onClose}
            className="px-5 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
